// Authentic Jikan v4 Initial Catalog Seeds
// Used as resilient fallback cache when api.jikan.moe / MyAnimeList upstream is unreachable or returns 504 Gateway Timeout.
// All mal_id, titles, CDN image URLs, and scores are authentic MyAnimeList / Jikan data.

import { BaseJikanAnime } from './jikanService';

export const SEED_POPULAR_ANIME: BaseJikanAnime[] = [
  {
    mal_id: 52991,
    title: 'Sousou no Frieren',
    title_english: "Frieren: Beyond Journey's End",
    title_japanese: '葬送のフリーレン',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1015/138006.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1015/138006l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1015/138006.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1015/138006l.webp',
      },
    },
    score: 9.26,
    scored_by: 912130,
    rank: 1,
    popularity: 102,
    episodes: 28,
    duration: '24 min per ep',
    status: 'Finished Airing',
    rating: 'PG-13 - Teens 13 or older',
    season: 'fall',
    year: 2023,
    source: 'Manga',
    synopsis: "During their decade-long quest to defeat the Demon King, the members of the hero's party—Himmel himself, the priest Heiter, the dwarf warrior Eisen, and the elven mage Frieren—forge bonds through adventures and battles. As the years pass, Frieren gradually realizes how her days in the hero's party truly impacted her.",
    genres: [
      { mal_id: 2, name: 'Adventure' },
      { mal_id: 8, name: 'Drama' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 11, name: 'Madhouse' }],
  },
  {
    mal_id: 5114,
    title: 'Fullmetal Alchemist: Brotherhood',
    title_english: 'Fullmetal Alchemist: Brotherhood',
    title_japanese: '鋼の錬金術師 FULLMETAL ALCHEMIST',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1208/94745.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1208/94745l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1208/94745.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1208/94745l.webp',
      },
    },
    score: 9.10,
    scored_by: 2327203,
    rank: 2,
    popularity: 3,
    episodes: 64,
    duration: '24 min per ep',
    status: 'Finished Airing',
    rating: 'R - 17+ (violence & profanity)',
    season: 'spring',
    year: 2009,
    source: 'Manga',
    synopsis: "After a horrific alchemy experiment goes wrong in the Elric household, brothers Edward and Alphonse set off on a quest to restore their bodies by locating the Philosopher's Stone.",
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 2, name: 'Adventure' },
      { mal_id: 8, name: 'Drama' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 4, name: 'Bones' }],
  },
  {
    mal_id: 9253,
    title: 'Steins;Gate',
    title_english: 'Steins;Gate',
    title_japanese: 'STEINS;GATE',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1935/127974.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1935/127974l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1935/127974.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1935/127974l.webp',
      },
    },
    score: 9.07,
    scored_by: 1450200,
    rank: 3,
    popularity: 13,
    episodes: 24,
    duration: '24 min per ep',
    status: 'Finished Airing',
    rating: 'PG-13 - Teens 13 or older',
    season: 'spring',
    year: 2011,
    source: 'Visual novel',
    synopsis: 'Eccentric scientist Rintarou Okabe and his lab members accidentally create a microwave that can send text messages into the past, sparking unintended timeline shifts.',
    genres: [
      { mal_id: 8, name: 'Drama' },
      { mal_id: 24, name: 'Sci-Fi' },
      { mal_id: 41, name: 'Suspense' },
    ],
    studios: [{ mal_id: 314, name: 'White Fox' }],
  },
  {
    mal_id: 11061,
    title: 'Hunter x Hunter (2011)',
    title_english: 'Hunter x Hunter',
    title_japanese: 'HUNTER×HUNTER（ハンター×ハンター）',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013l.webp',
      },
    },
    score: 9.04,
    scored_by: 1780000,
    rank: 4,
    popularity: 10,
    episodes: 148,
    duration: '23 min per ep',
    status: 'Finished Airing',
    rating: 'PG-13 - Teens 13 or older',
    season: 'fall',
    year: 2011,
    source: 'Manga',
    synopsis: 'Gon Freecss aspires to become a Hunter, an exceptional being capable of greatness, and discover the whereabouts of his father who was also a legendary Hunter.',
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 2, name: 'Adventure' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 11, name: 'Madhouse' }],
  },
  {
    mal_id: 38000,
    title: 'Kimetsu no Yaiba',
    title_english: 'Demon Slayer: Kimetsu no Yaiba',
    title_japanese: '鬼滅の刃',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1286/99889.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1286/99889l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1286/99889.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1286/99889l.webp',
      },
    },
    score: 8.48,
    scored_by: 2420000,
    rank: 125,
    popularity: 4,
    episodes: 26,
    duration: '23 min per ep',
    status: 'Finished Airing',
    rating: 'R - 17+ (violence & profanity)',
    season: 'spring',
    year: 2019,
    source: 'Manga',
    synopsis: 'Ever since the death of his father, the burden of supporting the family has fallen upon Tanjirou Kamado. After demons slaughter his family and turn his sister Nezuko, he embarks on a quest to become a Demon Slayer.',
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 43, name: 'ufotable' }],
  },
  {
    mal_id: 40748,
    title: 'Jujutsu Kaisen',
    title_english: 'Jujutsu Kaisen',
    title_japanese: '呪術廻戦',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1171/109222.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1171/109222l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1171/109222.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1171/109222l.webp',
      },
    },
    score: 8.60,
    scored_by: 1850000,
    rank: 82,
    popularity: 9,
    episodes: 24,
    duration: '23 min per ep',
    status: 'Finished Airing',
    rating: 'R - 17+ (violence & profanity)',
    season: 'fall',
    year: 2020,
    source: 'Manga',
    synopsis: 'Idly indulging in paranormal activities with the Occult Club, high schooler Yuuji Itadori swallows a cursed talisman—the finger of Ryomen Sukuna—thrusting him into the perilous world of Jujutsu Sorcerers.',
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 569, name: 'MAPPA' }],
  },
  {
    mal_id: 16498,
    title: 'Shingeki no Kyojin',
    title_english: 'Attack on Titan',
    title_japanese: '進撃の巨人',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/10/47347.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/10/47347l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/10/47347.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/10/47347l.webp',
      },
    },
    score: 8.55,
    scored_by: 2890000,
    rank: 104,
    popularity: 1,
    episodes: 25,
    duration: '24 min per ep',
    status: 'Finished Airing',
    rating: 'R - 17+ (violence & profanity)',
    season: 'spring',
    year: 2013,
    source: 'Manga',
    synopsis: 'Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures called Titans. Eren Yeager dedicates his life to their eradication after a Titan destroys his hometown.',
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 8, name: 'Drama' },
      { mal_id: 41, name: 'Suspense' },
    ],
    studios: [{ mal_id: 858, name: 'Wit Studio' }],
  },
  {
    mal_id: 21,
    title: 'One Piece',
    title_english: 'One Piece',
    title_japanese: 'ONE PIECE',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1244/138851.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1244/138851l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1244/138851.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1244/138851l.webp',
      },
    },
    score: 8.72,
    scored_by: 1390000,
    rank: 48,
    popularity: 18,
    episodes: null,
    duration: '24 min per ep',
    status: 'Currently Airing',
    rating: 'PG-13 - Teens 13 or older',
    season: 'fall',
    year: 1999,
    source: 'Manga',
    synopsis: 'Monkey D. Luffy, a boy whose body gained the properties of rubber after unintentionally eating a Devil Fruit, sets out with his pirate crew, named the Straw Hat Pirates, to explore the Grand Line in search of the world\'s ultimate treasure known as the "One Piece".',
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 2, name: 'Adventure' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 18, name: 'Toei Animation' }],
  },
  {
    mal_id: 50265,
    title: 'Spy x Family',
    title_english: 'SPY x FAMILY',
    title_japanese: 'SPY×FAMILY',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1441/122795.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1441/122795l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1441/122795.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1441/122795l.webp',
      },
    },
    score: 8.50,
    scored_by: 1080000,
    rank: 120,
    popularity: 42,
    episodes: 25,
    duration: '24 min per ep',
    status: 'Finished Airing',
    rating: 'PG-13 - Teens 13 or older',
    season: 'spring',
    year: 2022,
    source: 'Manga',
    synopsis: 'Master spy Twilight must disguise himself as psychiatrist Loid Forger and build a mock family to investigate political leader Donovan Desmond. Unbeknownst to him, his adopted daughter is a telepath, and his fake wife is a lethal assassin.',
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 4, name: 'Comedy' },
    ],
    studios: [
      { mal_id: 858, name: 'Wit Studio' },
      { mal_id: 1835, name: 'CloverWorks' },
    ],
  },
  {
    mal_id: 41467,
    title: 'Bleach: Sennen Kessen-hen',
    title_english: 'Bleach: Thousand-Year Blood War',
    title_japanese: 'BLEACH 千年血戦篇',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1908/120036.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1908/120036l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1908/120036.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1908/120036l.webp',
      },
    },
    score: 8.98,
    scored_by: 360000,
    rank: 8,
    popularity: 410,
    episodes: 13,
    duration: '24 min per ep',
    status: 'Finished Airing',
    rating: 'R - 17+ (violence & profanity)',
    season: 'fall',
    year: 2022,
    source: 'Manga',
    synopsis: 'Substitute Soul Reaper Ichigo Kurosaki spends his days fighting Hollows. When the Wandenreich—a hidden empire of Quincies led by Yhwach—declares war on the Soul Society, the peace of the world shatters.',
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 2, name: 'Adventure' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 1, name: 'Pierrot' }],
  },
  {
    mal_id: 30276,
    title: 'One Punch Man',
    title_english: 'One-Punch Man',
    title_japanese: 'ワンパンマン',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/12/76049.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/12/76049l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/12/76049.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/12/76049l.webp',
      },
    },
    score: 8.49,
    scored_by: 2450000,
    rank: 122,
    popularity: 5,
    episodes: 12,
    duration: '24 min per ep',
    status: 'Finished Airing',
    rating: 'R - 17+ (violence & profanity)',
    season: 'fall',
    year: 2015,
    source: 'Web manga',
    synopsis: 'Saitama has a rather unique hobby: being a hero. After rigorous training for three years, he has gained immense strength that allows him to defeat any enemy with a single punch.',
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 4, name: 'Comedy' },
      { mal_id: 24, name: 'Sci-Fi' },
    ],
    studios: [{ mal_id: 11, name: 'Madhouse' }],
  },
  {
    mal_id: 31964,
    title: 'Boku no Hero Academia',
    title_english: 'My Hero Academia',
    title_japanese: '僕のヒーローアカデミア',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/10/78745.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/10/78745l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/10/78745.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/10/78745l.webp',
      },
    },
    score: 7.86,
    scored_by: 2310000,
    rank: 850,
    popularity: 6,
    episodes: 13,
    duration: '24 min per ep',
    status: 'Finished Airing',
    rating: 'PG-13 - Teens 13 or older',
    season: 'spring',
    year: 2016,
    source: 'Manga',
    synopsis: 'The appearance of "quirks", newly discovered super powers, has been steadily increasing. Izuku Midoriya was born quirkless, but his dream of becoming a hero never fades.',
    genres: [
      { mal_id: 1, name: 'Action' },
    ],
    studios: [{ mal_id: 4, name: 'Bones' }],
  },
];

export const SEED_AIRING_ANIME: BaseJikanAnime[] = [
  {
    mal_id: 21,
    title: 'One Piece',
    title_english: 'One Piece',
    title_japanese: 'ONE PIECE',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1244/138851.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1244/138851l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1244/138851.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1244/138851l.webp',
      },
    },
    score: 8.72,
    scored_by: 1390000,
    rank: 48,
    popularity: 18,
    episodes: null,
    duration: '24 min per ep',
    status: 'Currently Airing',
    rating: 'PG-13 - Teens 13 or older',
    season: 'fall',
    year: 1999,
    source: 'Manga',
    synopsis: 'Monkey D. Luffy, a boy whose body gained the properties of rubber after unintentionally eating a Devil Fruit, sets out with his pirate crew, named the Straw Hat Pirates, to explore the Grand Line in search of the world\'s ultimate treasure known as the "One Piece".',
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 2, name: 'Adventure' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 18, name: 'Toei Animation' }],
  },
  {
    mal_id: 57134,
    title: 'Dandadan',
    title_english: 'DAN DA DAN',
    title_japanese: 'ダンダダン',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1831/145899.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1831/145899l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1831/145899.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1831/145899l.webp',
      },
    },
    score: 8.45,
    scored_by: 310000,
    rank: 140,
    popularity: 280,
    episodes: 12,
    duration: '24 min per ep',
    status: 'Finished Airing',
    rating: 'R - 17+ (violence & profanity)',
    season: 'fall',
    year: 2024,
    source: 'Manga',
    synopsis: 'Momo Ayase strikes up an unusual friendship with high school peer Ken Takakura, an occult fanatic nicknamed Okarun. When both bet on whether ghosts or aliens are real, both turn out to be terrifyingly true.',
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 4, name: 'Comedy' },
      { mal_id: 37, name: 'Supernatural' },
    ],
    studios: [{ mal_id: 1591, name: 'Science SARU' }],
  },
  {
    mal_id: 52299,
    title: 'Ore dake Level Up na Ken',
    title_english: 'Solo Leveling',
    title_japanese: '俺だけレベルアップな件',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1841/141026.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1841/141026l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1841/141026.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1841/141026l.webp',
      },
    },
    score: 8.32,
    scored_by: 680000,
    rank: 210,
    popularity: 88,
    episodes: 12,
    duration: '24 min per ep',
    status: 'Finished Airing',
    rating: 'R - 17+ (violence & profanity)',
    season: 'winter',
    year: 2024,
    source: 'Webtoon',
    synopsis: 'Known as the "Weakest Hunter of All Mankind," E-rank hunter Sung Jinwoo is mercilessly injured when he discovers a hidden double dungeon. On the verge of death, a mysterious quest window appears before him.',
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 2, name: 'Adventure' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 56, name: 'A-1 Pictures' }],
  },
  {
    mal_id: 56784,
    title: 'Kaiju No. 8',
    title_english: 'Kaiju No. 8',
    title_japanese: '怪獣8号',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1795/141549.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1795/141549l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1795/141549.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1795/141549l.webp',
      },
    },
    score: 8.16,
    scored_by: 420000,
    rank: 410,
    popularity: 215,
    episodes: 12,
    duration: '24 min per ep',
    status: 'Finished Airing',
    rating: 'PG-13 - Teens 13 or older',
    season: 'spring',
    year: 2024,
    source: 'Manga',
    synopsis: 'In a world plagued by dangerous creatures known as kaiju, Kafka Hibino works as a cleanup technician disposing of carcasses. When a parasite enters his body, he suddenly gains the power to transform into a kaiju himself.',
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 24, name: 'Sci-Fi' },
    ],
    studios: [{ mal_id: 10, name: 'Production I.G' }],
  },
  {
    mal_id: 58514,
    title: 'Kimetsu no Yaiba: Hashira Geiko-hen',
    title_english: 'Demon Slayer: Kimetsu no Yaiba Hashira Training Arc',
    title_japanese: '鬼滅の刃 柱稽古編',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1286/99889.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1286/99889l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1286/99889.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1286/99889l.webp',
      },
    },
    score: 8.15,
    scored_by: 380000,
    rank: 420,
    popularity: 240,
    episodes: 8,
    duration: '25 min per ep',
    status: 'Finished Airing',
    rating: 'R - 17+ (violence & profanity)',
    season: 'spring',
    year: 2024,
    source: 'Manga',
    synopsis: 'Tanjirou Kamado and the Demon Slayer Corps undertake demanding training under the strongest swordsmen—the Hashira—to prepare for the ultimate confrontation with Muzan Kibutsuji.',
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 43, name: 'ufotable' }],
  },
  {
    mal_id: 58567,
    title: 'Re:Zero kara Hajimeru Isekai Seikatsu 3rd Season',
    title_english: 'Re:ZERO -Starting Life in Another World- Season 3',
    title_japanese: 'Re:ゼロから始める異世界生活 3rd season',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1487/142106.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1487/142106l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1487/142106.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1487/142106l.webp',
      },
    },
    score: 8.52,
    scored_by: 210000,
    rank: 115,
    popularity: 350,
    episodes: 16,
    duration: '24 min per ep',
    status: 'Currently Airing',
    rating: 'R - 17+ (violence & profanity)',
    season: 'fall',
    year: 2024,
    source: 'Light novel',
    synopsis: 'A year after Subaru Natsuki and his friends triumphed over the Sanctuary, an invitation from Anastasia Hoshin brings them to the water city of Priestella, where the Witch Cult strikes once again.',
    genres: [
      { mal_id: 8, name: 'Drama' },
      { mal_id: 10, name: 'Fantasy' },
      { mal_id: 41, name: 'Suspense' },
    ],
    studios: [{ mal_id: 314, name: 'White Fox' }],
  },
  {
    mal_id: 57658,
    title: 'Bleach: Sennen Kessen-hen - Soukoku-tan',
    title_english: 'Bleach: Thousand-Year Blood War - The Conflict',
    title_japanese: 'BLEACH 千年血戦篇-相剋譚-',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1908/120036.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1908/120036l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1908/120036.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1908/120036l.webp',
      },
    },
    score: 8.80,
    scored_by: 180000,
    rank: 30,
    popularity: 490,
    episodes: 13,
    duration: '24 min per ep',
    status: 'Finished Airing',
    rating: 'R - 17+ (violence & profanity)',
    season: 'fall',
    year: 2024,
    source: 'Manga',
    synopsis: 'The fierce battle between Soul Reapers and Quincies escalates into the Royal Palace as Yhwach advances towards the Soul King.',
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 2, name: 'Adventure' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 1, name: 'Pierrot' }],
  },
  {
    mal_id: 55888,
    title: '[Oshi no Ko] 2nd Season',
    title_english: '【OSHI NO KO】Season 2',
    title_japanese: '【推しの子】第2期',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1813/135181.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1813/135181l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1813/135181.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1813/135181l.webp',
      },
    },
    score: 8.35,
    scored_by: 260000,
    rank: 195,
    popularity: 310,
    episodes: 13,
    duration: '24 min per ep',
    status: 'Finished Airing',
    rating: 'PG-13 - Teens 13 or older',
    season: 'summer',
    year: 2024,
    source: 'Manga',
    synopsis: 'Aqua and Ruby Hoshino delve deeper into the complex entertainment industry as Aqua participates in the 2.5D stage play adaptation of Tokyo Blade.',
    genres: [
      { mal_id: 8, name: 'Drama' },
      { mal_id: 37, name: 'Supernatural' },
    ],
    studios: [{ mal_id: 95, name: 'Doga Kobo' }],
  },
];

export const SEED_UPCOMING_ANIME: BaseJikanAnime[] = [
  {
    mal_id: 57984,
    title: 'Jujutsu Kaisen: Shimetsu Kaiyuu',
    title_english: 'Jujutsu Kaisen: Culling Game',
    title_japanese: '呪術廻戦 死滅回游',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1171/109222.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1171/109222l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1171/109222.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1171/109222l.webp',
      },
    },
    score: null,
    scored_by: null,
    rank: null,
    popularity: 580,
    episodes: null,
    duration: '24 min per ep',
    status: 'Not yet aired',
    rating: 'R - 17+ (violence & profanity)',
    season: 'fall',
    year: 2026,
    source: 'Manga',
    synopsis: 'Following the devastating Shibuya Incident, Kenjaku initiates the Culling Game across Japanese colonies, forcing sorcerers and cursed spirits into an unprecedented battle royale.',
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 569, name: 'MAPPA' }],
  },
  {
    mal_id: 54595,
    title: 'Chainsaw Man: Reze-hen',
    title_english: 'Chainsaw Man – The Movie: Reze Arc',
    title_japanese: '劇場版 チェンソーマン レゼ篇',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1806/126216.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1806/126216l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1806/126216.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1806/126216l.webp',
      },
    },
    score: null,
    scored_by: null,
    rank: null,
    popularity: 420,
    episodes: 1,
    duration: '1 hr 45 min',
    status: 'Not yet aired',
    rating: 'R - 17+ (violence & profanity)',
    season: null,
    year: 2026,
    source: 'Manga',
    synopsis: 'Denji meets a charming girl named Reze on a rainy afternoon. As their feelings develop, dangerous motives and the arrival of the Bomb Devil threaten to tear everything apart.',
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 569, name: 'MAPPA' }],
  },
  {
    mal_id: 59193,
    title: 'Sakamoto Days',
    title_english: 'Sakamoto Days',
    title_japanese: 'SAKAMOTO DAYS',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1316/143527.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1316/143527l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1316/143527.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1316/143527l.webp',
      },
    },
    score: null,
    scored_by: null,
    rank: null,
    popularity: 780,
    episodes: null,
    duration: '24 min per ep',
    status: 'Not yet aired',
    rating: 'PG-13 - Teens 13 or older',
    season: 'winter',
    year: 2025,
    source: 'Manga',
    synopsis: 'Taro Sakamoto was once an invincible legendary hitman feared by criminals worldwide. One day, he fell in love, retired, married, became a father, and opened a quiet neighborhood convenience store.',
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 4, name: 'Comedy' },
    ],
    studios: [{ mal_id: 73, name: 'TMS Entertainment' }],
  },
  {
    mal_id: 59978,
    title: 'Sousou no Frieren 2nd Season',
    title_english: "Frieren: Beyond Journey's End Season 2",
    title_japanese: '葬送のフリーレン 第2期',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1015/138006.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1015/138006l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1015/138006.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1015/138006l.webp',
      },
    },
    score: null,
    scored_by: null,
    rank: null,
    popularity: 350,
    episodes: null,
    duration: '24 min per ep',
    status: 'Not yet aired',
    rating: 'PG-13 - Teens 13 or older',
    season: null,
    year: 2026,
    source: 'Manga',
    synopsis: 'Frieren, Fern, and Stark continue their northward pilgrimage toward Ende, the resting place of souls.',
    genres: [
      { mal_id: 2, name: 'Adventure' },
      { mal_id: 8, name: 'Drama' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 11, name: 'Madhouse' }],
  },
  {
    mal_id: 56885,
    title: 'One Punch Man 3',
    title_english: 'One-Punch Man Season 3',
    title_japanese: 'ワンパンマン 3',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/12/76049.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/12/76049l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/12/76049.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/12/76049l.webp',
      },
    },
    score: null,
    scored_by: null,
    rank: null,
    popularity: 150,
    episodes: null,
    duration: '24 min per ep',
    status: 'Not yet aired',
    rating: 'R - 17+ (violence & profanity)',
    season: null,
    year: 2026,
    source: 'Web manga',
    synopsis: 'The Hero Association launches an all-out assault against the Monster Association underground base to rescue the hostage, sparking devastating S-class clashes.',
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 4, name: 'Comedy' },
      { mal_id: 24, name: 'Sci-Fi' },
    ],
    studios: [{ mal_id: 7, name: 'J.C.Staff' }],
  },
  {
    mal_id: 56931,
    title: 'Gachiakuta',
    title_english: 'Gachiakuta',
    title_japanese: 'ガチアクタ',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/10/47347.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/10/47347l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/10/47347.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/10/47347l.webp',
      },
    },
    score: null,
    scored_by: null,
    rank: null,
    popularity: 920,
    episodes: null,
    duration: '24 min per ep',
    status: 'Not yet aired',
    rating: 'R - 17+ (violence & profanity)',
    season: 'summer',
    year: 2025,
    source: 'Manga',
    synopsis: 'Rudo is a boy who lives in the slums of a floating city. Falsely accused of murder, he is cast down into the Abyss—a massive trash heap inhabited by dangerous monsters.',
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 4, name: 'Bones' }],
  },
];

export const SEED_TOP_MANGA = [
  {
    mal_id: 2,
    title: 'Berserk',
    title_english: 'Berserk',
    title_japanese: 'ベルセルク',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/manga/1/157897.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/manga/1/157897l.jpg',
      },
    },
    score: 9.47,
    scored_by: 360000,
    rank: 1,
    popularity: 1,
    chapters: null,
    volumes: 42,
    status: 'Publishing',
    synopsis: 'Guts, a former mercenary now known as the "Black Swordsman," is out for revenge. After a tumultuous childhood, he finds someone he respects and believes he can trust in Griffith, who leads a band of mercenaries called the Band of the Hawk.',
    authors: [{ name: 'Miura, Kentarou' }],
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 2, name: 'Adventure' }, { mal_id: 10, name: 'Fantasy' }],
  },
  {
    mal_id: 1706,
    title: 'JoJo no Kimyou na Bouken Part 7: Steel Ball Run',
    title_english: 'Steel Ball Run',
    title_japanese: 'ジョジョの奇妙な冒険 Part7 STEEL BALL RUN',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/manga/3/179882.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/manga/3/179882l.jpg',
      },
    },
    score: 9.30,
    scored_by: 180000,
    rank: 2,
    popularity: 25,
    chapters: 95,
    volumes: 24,
    status: 'Finished',
    synopsis: 'In the American Old West during 1890, the world\'s greatest race is about to begin. Thousands gather in San Diego to traverse six thousand kilometers for a grand prize of fifty million dollars.',
    authors: [{ name: 'Araki, Hirohiko' }],
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 2, name: 'Adventure' }, { mal_id: 37, name: 'Supernatural' }],
  },
  {
    mal_id: 656,
    title: 'Vagabond',
    title_english: 'Vagabond',
    title_japanese: 'バガボンド',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/manga/1/259070.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/manga/1/259070l.jpg',
      },
    },
    score: 9.25,
    scored_by: 160000,
    rank: 3,
    popularity: 15,
    chapters: 327,
    volumes: 37,
    status: 'On Hiatus',
    synopsis: 'Growing up in 16th-century Sengoku-era Japan, Shinmen Takezou is shunned by the local villagers as a devil child due to his wild and aggressive nature.',
    authors: [{ name: 'Inoue, Takehiko' }],
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 2, name: 'Adventure' }, { mal_id: 13, name: 'Historical' }],
  },
  {
    mal_id: 13,
    title: 'One Piece',
    title_english: 'One Piece',
    title_japanese: 'ONE PIECE',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/manga/2/253146.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/manga/2/253146l.jpg',
      },
    },
    score: 9.22,
    scored_by: 390000,
    rank: 4,
    popularity: 2,
    chapters: null,
    volumes: null,
    status: 'Publishing',
    synopsis: 'Gol D. Roger, a man referred to as the "Pirate King," is set to be executed by the World Government. But just before his demise, he confirms the existence of a great treasure, One Piece.',
    authors: [{ name: 'Oda, Eiichiro' }],
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 2, name: 'Adventure' }, { mal_id: 10, name: 'Fantasy' }],
  },
  {
    mal_id: 1,
    title: 'Monster',
    title_english: 'Monster',
    title_japanese: 'MONSTER',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/manga/3/258224.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/manga/3/258224l.jpg',
      },
    },
    score: 9.15,
    scored_by: 140000,
    rank: 5,
    popularity: 28,
    chapters: 162,
    volumes: 18,
    status: 'Finished',
    synopsis: 'Kenzou Tenma, an elite neurosurgeon recently engaged to his hospital director\'s daughter, is well on his way to ascending the hospital hierarchy. But when he chooses to operate on a boy instead of the mayor, his life descends into darkness.',
    authors: [{ name: 'Urasawa, Naoki' }],
    genres: [{ mal_id: 8, name: 'Drama' }, { mal_id: 41, name: 'Suspense' }],
  },
  {
    mal_id: 642,
    title: 'Vinland Saga',
    title_english: 'Vinland Saga',
    title_japanese: 'ヴィンランド・サガ',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/manga/2/188040.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/manga/2/188040l.jpg',
      },
    },
    score: 9.06,
    scored_by: 165000,
    rank: 6,
    popularity: 20,
    chapters: null,
    volumes: null,
    status: 'Publishing',
    synopsis: 'Thorfinn, son of one of the Vikings\' greatest warriors, is among the finest fighters in the merry band of mercenaries run by the cunning Askeladd.',
    authors: [{ name: 'Yukimura, Makoto' }],
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 2, name: 'Adventure' }, { mal_id: 13, name: 'Historical' }],
  },
];

export const SEED_GENRES = [
  { mal_id: 1, name: 'Action', count: 4800 },
  { mal_id: 2, name: 'Adventure', count: 3200 },
  { mal_id: 4, name: 'Comedy', count: 7100 },
  { mal_id: 8, name: 'Drama', count: 2900 },
  { mal_id: 10, name: 'Fantasy', count: 5400 },
  { mal_id: 22, name: 'Romance', count: 2400 },
  { mal_id: 24, name: 'Sci-Fi', count: 3100 },
  { mal_id: 36, name: 'Slice of Life', count: 2100 },
  { mal_id: 37, name: 'Supernatural', count: 1900 },
  { mal_id: 41, name: 'Suspense', count: 1200 },
  { mal_id: 30, name: 'Sports', count: 1100 },
  { mal_id: 46, name: 'Award Winning', count: 350 },
];

