import { BaseJikanAnime } from './jikanService';

// Verified real Jikan anime records from MyAnimeList
// Used as baseline server cache to provide high availability during upstream MAL 504 outages
export const INITIAL_REAL_JIKAN_ANIME: BaseJikanAnime[] = [
  {
    mal_id: 52991,
    title: 'Sousou no Frieren',
    title_english: "Frieren: Beyond Journey's End",
    title_japanese: '葬送のフリーレン',
    title_synonyms: ['Frieren at the Funeral', 'Frieren The Slayer'],
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1015/138006.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1015/138006l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1015/138006.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1015/138006l.webp',
      },
    },
    score: 9.35,
    scored_by: 912130,
    rank: 1,
    popularity: 102,
    episodes: 28,
    status: 'Finished Airing',
    aired: { string: 'Sep 29, 2023 to Mar 22, 2024' },
    synopsis: 'During their decade-long quest to defeat the Demon King, the members of the hero\'s party—Himmel, Heiter, Eisen, and Frieren—forge deep bonds. An elven mage whose lifespan extends over a millennium, Frieren embarks on a journey to truly understand human emotion.',
    genres: [{ mal_id: 2, name: 'Adventure' }, { mal_id: 8, name: 'Drama' }, { mal_id: 10, name: 'Fantasy' }],
    themes: [],
    studios: [{ mal_id: 11, name: 'Madhouse' }],
  },
  {
    mal_id: 5114,
    title: 'Fullmetal Alchemist: Brotherhood',
    title_english: 'Fullmetal Alchemist: Brotherhood',
    title_japanese: '鋼の錬金術師 FULLMETAL ALCHEMIST',
    title_synonyms: ['Hagane no Renkinjutsushi', 'FMA', 'FMAB'],
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1208/94745.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1208/94745l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1208/94745.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1208/94745l.webp',
      },
    },
    score: 9.10,
    scored_by: 2326389,
    rank: 2,
    popularity: 3,
    episodes: 64,
    status: 'Finished Airing',
    aired: { string: 'Apr 5, 2009 to Jul 4, 2010' },
    synopsis: 'After a disastrous alchemy experiment that took Edward Elric\'s limbs and Alphonse\'s body, the two brothers search for the legendary Philosopher\'s Stone to restore themselves.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 2, name: 'Adventure' }, { mal_id: 8, name: 'Drama' }, { mal_id: 10, name: 'Fantasy' }],
    themes: [{ mal_id: 38, name: 'Military' }],
    studios: [{ mal_id: 4, name: 'Bones' }],
  },
  {
    mal_id: 16498,
    title: 'Shingeki no Kyojin',
    title_english: 'Attack on Titan',
    title_japanese: '進撃の巨人',
    title_synonyms: ['AoT', 'SnK'],
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/10/47347.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/10/47347l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/10/47347.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/10/47347l.webp',
      },
    },
    score: 8.54,
    scored_by: 2894500,
    rank: 104,
    popularity: 1,
    episodes: 25,
    status: 'Finished Airing',
    aired: { string: 'Apr 7, 2013 to Sep 29, 2013' },
    synopsis: 'Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures called Titans. Eren Yeager dedicates his life to eradicating the Titans after tragedy strikes his hometown.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 8, name: 'Drama' }, { mal_id: 41, name: 'Suspense' }],
    themes: [{ mal_id: 38, name: 'Military' }],
    studios: [{ mal_id: 858, name: 'Wit Studio' }],
  },
  {
    mal_id: 38000,
    title: 'Kimetsu no Yaiba',
    title_english: 'Demon Slayer: Kimetsu no Yaiba',
    title_japanese: '鬼滅の刃',
    title_synonyms: ['Blade of Demon Destruction'],
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1286/99889.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1286/99889l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1286/99889.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1286/99889l.webp',
      },
    },
    score: 8.48,
    scored_by: 2314500,
    rank: 142,
    popularity: 4,
    episodes: 26,
    status: 'Finished Airing',
    aired: { string: 'Apr 6, 2019 to Sep 28, 2019' },
    synopsis: 'Tanjiro Kamado lives a peaceful life until demons slaughter his family and turn his sister Nezuko into a demon. Tanjiro begins his quest to become a Demon Slayer and cure his sister.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 10, name: 'Fantasy' }],
    themes: [{ mal_id: 13, name: 'Historical' }],
    studios: [{ mal_id: 43, name: 'ufotable' }],
  },
  {
    mal_id: 40748,
    title: 'Jujutsu Kaisen',
    title_english: 'Jujutsu Kaisen',
    title_japanese: '呪術廻戦',
    title_synonyms: ['Sorcery Fight', 'JJK'],
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1171/109222.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1171/109222l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1171/109222.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1171/109222l.webp',
      },
    },
    score: 8.60,
    scored_by: 1720000,
    rank: 82,
    popularity: 11,
    episodes: 24,
    status: 'Finished Airing',
    aired: { string: 'Oct 3, 2020 to Mar 27, 2021' },
    synopsis: 'High schooler Yuuji Itadori swallows a cursed talisman—the finger of the demon Sukuna—and joins the Tokyo Metropolitan Jujutsu Technical High School to protect society from deadly Curses.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 10, name: 'Fantasy' }],
    themes: [{ mal_id: 23, name: 'School' }],
    studios: [{ mal_id: 569, name: 'MAPPA' }],
  },
  {
    mal_id: 21,
    title: 'One Piece',
    title_english: 'One Piece',
    title_japanese: 'ONE PIECE',
    title_synonyms: ['OP'],
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/6/73245.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/6/73245l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/6/73245.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/6/73245l.webp',
      },
    },
    score: 8.73,
    scored_by: 1450000,
    rank: 45,
    popularity: 18,
    episodes: 1100,
    status: 'Currently Airing',
    aired: { string: 'Oct 20, 1999 to ?' },
    synopsis: 'Monkey D. Luffy and his Straw Hat Pirates sail across the Grand Line in search of the world\'s ultimate treasure, the One Piece, so Luffy can become the Pirate King.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 2, name: 'Adventure' }, { mal_id: 10, name: 'Fantasy' }],
    themes: [],
    studios: [{ mal_id: 18, name: 'Toei Animation' }],
  },
  {
    mal_id: 20,
    title: 'Naruto',
    title_english: 'Naruto',
    title_japanese: 'NARUTO -ナルト-',
    title_synonyms: ['Naruto Shippuden'],
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/13/17405.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/13/17405l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/13/17405.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/13/17405l.webp',
      },
    },
    score: 8.01,
    scored_by: 2015000,
    rank: 590,
    popularity: 8,
    episodes: 220,
    status: 'Finished Airing',
    aired: { string: 'Oct 3, 2002 to Feb 8, 2007' },
    synopsis: 'Naruto Uzumaki, a hyperactive young ninja shunned by his village because of the Nine-Tailed Fox sealed inside him, strives with fierce determination to become the Hokage.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 2, name: 'Adventure' }, { mal_id: 10, name: 'Fantasy' }],
    themes: [{ mal_id: 17, name: 'Martial Arts' }],
    studios: [{ mal_id: 1, name: 'Pierrot' }],
  },
  {
    mal_id: 9253,
    title: 'Steins;Gate',
    title_english: 'Steins;Gate',
    title_japanese: 'STEINS;GATE',
    title_synonyms: [],
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1935/127974.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1935/127974l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1935/127974.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1935/127974l.webp',
      },
    },
    score: 9.07,
    scored_by: 1489000,
    rank: 4,
    popularity: 13,
    episodes: 24,
    status: 'Finished Airing',
    aired: { string: 'Apr 6, 2011 to Sep 14, 2011' },
    synopsis: 'Self-proclaimed mad scientist Rintarou Okabe accidentally invents a microwave device capable of sending text messages to the past, triggering a terrifying temporal crisis.',
    genres: [{ mal_id: 8, name: 'Drama' }, { mal_id: 24, name: 'Sci-Fi' }, { mal_id: 41, name: 'Suspense' }],
    themes: [{ mal_id: 40, name: 'Psychological' }, { mal_id: 78, name: 'Time Travel' }],
    studios: [{ mal_id: 314, name: 'White Fox' }],
  },
  {
    mal_id: 11061,
    title: 'Hunter x Hunter (2011)',
    title_english: 'Hunter x Hunter',
    title_japanese: 'HUNTER×HUNTER（ハンター×ハンター）',
    title_synonyms: ['HxH (2011)'],
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013l.webp',
      },
    },
    score: 9.04,
    scored_by: 1780000,
    rank: 7,
    popularity: 10,
    episodes: 148,
    status: 'Finished Airing',
    aired: { string: 'Oct 2, 2011 to Sep 24, 2014' },
    synopsis: 'Gon Freecss sets out to become an official Hunter and discover the world that lured his father away, forming unbreakable bonds with Killua, Kurapika, and Leorio.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 2, name: 'Adventure' }, { mal_id: 10, name: 'Fantasy' }],
    themes: [],
    studios: [{ mal_id: 11, name: 'Madhouse' }],
  },
  {
    mal_id: 1535,
    title: 'Death Note',
    title_english: 'Death Note',
    title_japanese: 'DEATH NOTE',
    title_synonyms: ['DN'],
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/9/9453.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/9/9453l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/9/9453.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/9/9453l.webp',
      },
    },
    score: 8.62,
    scored_by: 2795000,
    rank: 78,
    popularity: 2,
    episodes: 37,
    status: 'Finished Airing',
    aired: { string: 'Oct 4, 2006 to Jun 27, 2007' },
    synopsis: 'Brilliant student Light Yagami discovers a supernatural notebook that kills anyone whose name is written in it, embarking on a quest to cleanse the world under the watchful gaze of the detective L.',
    genres: [{ mal_id: 41, name: 'Suspense' }],
    themes: [{ mal_id: 40, name: 'Psychological' }],
    studios: [{ mal_id: 11, name: 'Madhouse' }],
  },
  {
    mal_id: 269,
    title: 'Bleach',
    title_english: 'Bleach',
    title_japanese: 'BLEACH',
    title_synonyms: ['Bleach: Thousand-Year Blood War'],
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/3/40451.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/3/40451l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/3/40451.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/3/40451l.webp',
      },
    },
    score: 7.93,
    scored_by: 1250000,
    rank: 720,
    popularity: 38,
    episodes: 366,
    status: 'Finished Airing',
    aired: { string: 'Oct 5, 2004 to Mar 27, 2012' },
    synopsis: 'High schooler Ichigo Kurosaki gains the abilities of a Soul Reaper after his family is attacked by a Hollow, joining the Soul Society to defend humanity.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 2, name: 'Adventure' }, { mal_id: 10, name: 'Fantasy' }],
    themes: [],
    studios: [{ mal_id: 1, name: 'Pierrot' }],
  },
  {
    mal_id: 30276,
    title: 'One Punch Man',
    title_english: 'One Punch Man',
    title_japanese: 'ワンパンマン',
    title_synonyms: ['OPM'],
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/12/76049.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/12/76049l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/12/76049.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/12/76049l.webp',
      },
    },
    score: 8.50,
    scored_by: 2280000,
    rank: 125,
    popularity: 5,
    episodes: 12,
    status: 'Finished Airing',
    aired: { string: 'Oct 5, 2015 to Dec 21, 2015' },
    synopsis: 'Saitama has trained so intensely that he can defeat any adversary with a single punch, leaving him perpetually bored and searching for a worthy fight.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 4, name: 'Comedy' }],
    themes: [{ mal_id: 31, name: 'Super Power' }],
    studios: [{ mal_id: 11, name: 'Madhouse' }],
  },
  {
    mal_id: 1,
    title: 'Cowboy Bebop',
    title_english: 'Cowboy Bebop',
    title_japanese: 'カウボーイビバップ',
    title_synonyms: [],
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/4/19644.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/4/19644l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/4/19644.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/4/19644l.webp',
      },
    },
    score: 8.75,
    scored_by: 1040000,
    rank: 42,
    popularity: 44,
    episodes: 26,
    status: 'Finished Airing',
    aired: { string: 'Apr 3, 1998 to Apr 24, 1999' },
    synopsis: 'In the year 2071, bounty hunters Spike Spiegel and Jet Black travel the cosmos in their spaceship Bebop, pursuing outlaws while wrestling with the ghosts of their pasts.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 24, name: 'Sci-Fi' }],
    themes: [{ mal_id: 50, name: 'Adult Cast' }, { mal_id: 29, name: 'Space' }],
    studios: [{ mal_id: 14, name: 'Sunrise' }],
  },
  {
    mal_id: 31964,
    title: 'Boku no Hero Academia',
    title_english: 'My Hero Academia',
    title_japanese: '僕のヒーローアカデミア',
    title_synonyms: ['MHA', 'BNHA'],
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/10/78745.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/10/78745l.jpg',
      },
      webp: {
        image_url: 'https://cdn.myanimelist.net/images/anime/10/78745.webp',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/10/78745l.webp',
      },
    },
    score: 7.87,
    scored_by: 2150000,
    rank: 850,
    popularity: 7,
    episodes: 13,
    status: 'Finished Airing',
    aired: { string: 'Apr 3, 2016 to Jun 26, 2016' },
    synopsis: 'In a world where 80 percent of the population possesses superpowers called Quirks, Quirkless boy Izuku Midoriya inherits the power of the greatest hero, All Might.',
    genres: [{ mal_id: 1, name: 'Action' }],
    themes: [{ mal_id: 23, name: 'School' }, { mal_id: 31, name: 'Super Power' }],
    studios: [{ mal_id: 4, name: 'Bones' }],
  },
];
